tom_admin_dashboard:
    resource: "@TomAdminBundle/Controller/DashboardController.php"
    type: annotation
    prefix: /
    
tom_admin_pages:
    resource: "@TomAdminBundle/Controller/PagesController.php"
    type: annotation
    prefix: /strony 
    
tom_admin_menu_types:
    resource: "@TomAdminBundle/Controller/MenuTypesController.php"
    type: annotation
    prefix: /menu/typy
    
tom_admin_menu:
    resource: "@TomAdminBundle/Controller/MenuController.php"
    type: annotation
    prefix: /menu
    
tom_admin_slider_categories:
    resource: "@TomAdminBundle/Controller/SliderCategoriesController.php"
    type: annotation
    prefix: /slider/kategorie
    
tom_admin_slider:
    resource: "@TomAdminBundle/Controller/SliderController.php"
    type: annotation
    prefix: /slider
    
tom_admin_article_categories:
    resource: "@TomAdminBundle/Controller/ArticleCategoriesController.php"
    type: annotation
    prefix: /artykuly/kategorie

tom_admin_article_tags:
    resource: "@TomAdminBundle/Controller/ArticleTagsController.php"
    type: annotation
    prefix: /artykuly/tagi
    
tom_admin_articles:
    resource: "@TomAdminBundle/Controller/ArticlesController.php"
    type: annotation
    prefix: /artykuly
    
tom_admin_settings:
    resource: "@TomAdminBundle/Controller/SettingsController.php"
    type: annotation
    prefix: /ustawienia