services:
    tom_site.twig.extension.site:
        class: Tom\SiteBundle\Twig\Extension\SiteExtension
        arguments: ["@doctrine"]
        tags:
            - { name: twig.extension }
            
    tom_site.menu_builder:
        class: Tom\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine"]

    tom_site.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@tom_site.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }